### ISSUE TITLE
Debian build for v0.18.0

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/builds#10]
@szepeviktor Mind putting one together when you have a moment? The script doesn't work for me.

**Comment by szepeviktor** [comment]
Here you are https://github.com/wp-cli/wp-cli/pull/1807

**Comment by szepeviktor** [comment]
Please consider signing it.
For example my key can be obtained by `apt-key adv --keyserver pgp.mit.edu --recv-keys 451A4FBA`.

**Comment by danielbachhuber** [comment]
Oh, I meant, can you actually create the build? I have some script execution failure locally.

**Comment by szepeviktor** [comment]
https://github.com/wp-cli/builds/pull/11

**Comment by danielbachhuber** [comment]
:clap:

**Comment by szepeviktor** [comment]
Watch out! Issue's title = v0.18.0, not 19.

**Comment by szepeviktor** [comment]
18.deb is actually missing.
