### ISSUE TITLE
Please version/tag your builds

### ISSUE THREAD

**Issue by duritong** [wp-cli/builds#18]
In RPM build scripts I would like to reference to phar builds with versioned urls. At the moment there is only one URL/file that references the latest build.
It would be nice if you would either make the filenames containing the version (latest could still be symlinked) and/or tag the commits that introduce a new version, so that one would be able to fetch the phar from somehow versioned URLS.

Or any other ideas/suggestions how I could always fetch the right version? I can reference the commit, but then I always have to lookup and exchange the commit-sha1 and not only update the version within my build scripts.

**Comment by duritong** [comment]
I should look at the right place: https://github.com/wp-cli/wp-cli/releases Sorry for the noise...

**Comment by danielbachhuber** [comment]
No worries. I've [added a README](https://github.com/wp-cli/builds/blob/gh-pages/README.md) for this sort of question in the future.
