### ISSUE TITLE
Use a stronger hash algo for checksums

### ISSUE THREAD

**Issue by duritong** [wp-cli/builds#19]
It would be nice if we would not only for the nightly builds have sha512 checksums

**Comment by danielbachhuber** [comment]
Good suggestion. I've added `wp-cli.phar.sha512` for the latest release, and will make sure updating it is a part of the [release checklist](https://github.com/wp-cli/wp-cli/wiki/Release-Checklist) going forward.

**Comment by duritong** [comment]
Awesome, thanks!
Just a suggestion: It would be nice if the checksum also appears on the releases page, even better would be a gpg-signed checksum file.
