### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by fenix011** [wp-cli/builds#22]
On Debian GNU / Linux 8 i'm getting this error message 

`root@i-ching:/usr/local/bin# dpkg -i php-wpcli_0.20.1_all.deb 
dpkg-deb: error: `php-wpcli_0.20.1_all.deb' is not a debian format archive
dpkg: error processing archive php-wpcli_0.20.1_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 php-wpcli_0.20.1_all.deb`

**Comment by danielbachhuber** [comment]
cc @szepeviktor

**Comment by szepeviktor** [comment]
???

```
$ lintian php-wpcli_0.20.1_all.deb
E: php-wpcli: changelog-file-missing-in-native-package
E: php-wpcli: no-copyright-file
W: php-wpcli: binary-without-manpage usr/bin/wp
```

```
$ dpkg -i php-wpcli_0.20.1_all.deb
Selecting previously unselected package php-wpcli.
(Reading database ... 111650 files and directories currently installed.)
Preparing to unpack php-wpcli_0.20.1_all.deb ...
Unpacking php-wpcli (0.20.1) ...
Setting up php-wpcli (0.20.1) ...
[root@szerver4:/tmp:21:57:54:507]
```

**Comment by szepeviktor** [comment]
@jordila Please check your downloaded copy with lintian and try to download it again:
`wget https://github.com/wp-cli/builds/raw/gh-pages/deb/php-wpcli_0.20.1_all.deb`

**Comment by fenix011** [comment]
@szepeviktor for whatever reason, the at [wp-cli.org referred .deb package ](https://github.com/wp-cli/builds/blob/gh-pages/deb/php-wpcli_0.20.1_all.deb)  gave the problem.
`wget https://github.com/wp-cli/builds/raw/gh-pages/deb/php-wpcli_0.20.1_all.deb` works fine.

**Comment by szepeviktor** [comment]
I think https://github.com/wp-cli/builds/blob/gh-pages/deb/php-wpcli_0.20.1_all.deb
is an HTML page.

**Comment by szepeviktor** [comment]
@jordila Please give me the URL where this link can be found.

**Comment by fenix011** [comment]
@szepeviktor please find it at https://github.com/wp-cli/wp-cli/wiki/Alternative-Install-Methods , in the _Installing via .deb package_ section

**Comment by szepeviktor** [comment]
The only link Debian-related I've found on that wiki page is:
https://github.com/wp-cli/builds/tree/gh-pages/deb

When a list of files are visible in GitHub, try to click on a file - e.g. `php-wpcli_0.20.1_all.deb` - and right-click on `Raw` button and select _Copy link location_ from the context menu, at least in Firefox. In Chrome it may be called _Copy link address_.
