### ISSUE TITLE
Create symlink to latest deb.

### ISSUE THREAD

**Issue by ypid** [wp-cli/builds#23]

**Comment by szepeviktor** [comment]
Here you are #24.

**Comment by szepeviktor** [comment]
@ypid Please close this issue.

**Comment by ypid** [comment]
> I don’t know the release build process but I thought more about an automated solution :smile:

**Comment by ypid** [comment]
What happens on next release?

**Comment by ypid** [comment]
Do I need to open an issue then again? :wink:

**Comment by danielbachhuber** [comment]
> What happens on next release?

Someone will update the symlink.

> Do I need to open an issue then again?

No, it's covered in the release checklist now. Please be polite.

**Comment by szepeviktor** [comment]
Here: https://github.com/wp-cli/wp-cli/wiki/Release-Checklist#updating-the-debian-build

**Comment by ypid** [comment]
All right. Thanks again for the quick solution :+1:
