### ISSUE TITLE
Building v.0.20.4

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/builds#30]
`php wp0204.phar --version`

PHP Warning:  require(phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/symfony/polyfill-mbstring/bootstrap.php): failed to open stream: phar error: "vendor/symfony/polyfill-mbstring/bootstrap.php" is not a file in phar "/home/viktor/wp-cliX/wp-cli/wp0204.phar" in phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/composer/autoload_real.php on line 59

PHP Fatal error:  require(): Failed opening required 'phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/symfony/polyfill-mbstring/bootstrap.php' (include_path='phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/phpunit/phpunit-mock-objects:phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/phpunit/php-token-stream:phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/phpunit/php-code-coverage:phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/phpunit/phpunit:phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in phar:///home/viktor/wp-cliX/wp-cli/wp0204.phar/vendor/composer/autoload_real.php on line 59

**Comment by szepeviktor** [comment]
```
git checkout v0.20.4
composer update
php utils/make-phar.php ./wp0204.phar
```

**Comment by danielbachhuber** [comment]
If you run `composer update`, you'll create a failed Phar. 

I guess I need to create a branch that includes https://github.com/wp-cli/wp-cli/pull/2249

**Comment by szepeviktor** [comment]
OK
