### ISSUE TITLE
php-wpcli_latest_all.deb should be a copy instead of a symlink

### ISSUE THREAD

**Issue by mlang38** [wp-cli/builds#34]
Hi,
if the "php-wpcli_latest_all.deb" is to provide easy downloading, it would be great if it were a copy of the latest deb, not a symlink. A symlink is unusable as is, whereas a copy could be downloaded by a wget in an automated provisioning script or recipe.

Please make a copy instead of linking in your building process.

Thank you :wink:

**Comment by szepeviktor** [comment]
Others are complaining too https://github.com/isaacs/github/issues/379

**Comment by szepeviktor** [comment]
Meanwhile

``` bash
LATEST="https://github.com/wp-cli/builds/raw/gh-pages/deb/php-wpcli_latest_all.deb"
wget "$(dirname "$LATEST")/$(wget -qO- "$LATEST")"
```
