### ISSUE TITLE
nothing happens after I run: wp plugin update --all

### ISSUE THREAD

**Issue by AddaxSoft** [wp-cli/builds#46]
![image](https://cloud.githubusercontent.com/assets/6898938/23724902/d17ea84e-044e-11e7-9dbe-7e318bec8769.png)

I'm using the latest version.

**Comment by danielbachhuber** [comment]
Hi @AddaxSoft,

Github issues aren't an appropriate venue for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. Please review http://wp-cli.org/#support

**Comment by AddaxSoft** [comment]
@danielbachhuber , how is this *not* a bug? 
wpcli doesn't echo back any error and yet fails to update plugin, I'm not running any special version of wordpress
