### ISSUE TITLE
Change deb package dependencies

### ISSUE THREAD

**Issue by leeps** [wp-cli/builds#54]
Currently, wp-cli .deb packages come with the following dependencies:
```
Depends: php5-cli (>= 5.3.29) | php-cli | php7-cli, php5-mysql | php5-mysqlnd | php7.0-mysql | php7.1-mysql, mysql-client | mariadb-client
```

There are some problems with this list:
- a package `php7-cli` does not exist. PHP 7 cli packages are named `php7.x-cli`.
- `mysql-client` or `mariadb-client` are not real dependencies, wp-cli runs fine without them installed (as long as phpX-mysql is)
- PHP 7.1 is available, as is PHP 7.2. If wp-cli does in fact run with those versions, the dependency list should include them to prevent people having to install older versions just to satisfy a dependency

I suggest the following "dependency" list:
```
Depends: php5-cli (>= 5.3.29) | php-cli | php7.0-cli | php7.1-cli | php7.2-cli, php5-mysql | php5-mysqlnd | php7.0-mysql | php7.1-mysql | php7.2-mysql
Recommends: mysql-client | mariadb-client
```

**Comment by szepeviktor** [comment]
> mysql-client or mariadb-client are not real dependencies, wp-cli runs fine without them installed (as long as phpX-mysql is)

WP-CLI starts the `mysql` command (binary)

See `wp help db`

**Comment by szepeviktor** [comment]
Feel free to send a PR for PHP cli-s: https://github.com/wp-cli/wp-cli/blob/master/utils/wp-cli-updatedeb.sh#L34

**Comment by leeps** [comment]
Thanks for pointing me in the right direction.
As far as I know, wp-cli only uses the mysql binary for a subset of its commands. I'll check again to see if any of those could be deemed essential or if am mistaken in this assumption.
Expect a PR within a week.
