### ISSUE TITLE
Nightly phar.asc missing

### ISSUE THREAD

**Issue by strarsis** [wp-cli/builds#59]
The nightly release `phar` has no `phar.asc` counterpart in this repository.
How can nightly release `phar` files be verified after download?
It would be nice to be able to use the same verification mechanism (`asc`) as with stable release `phars`, 
e.g. when provisioning a test/staging server with a nightly WP CLI release.
The `asc` of the stable release `phar` doesn't pass for the nightly `phar`.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @strarsis 

An important distinction:
* The nightly build is created in the CI environment.
* The `asc` signature mechanism is produced locally.

If the environment expects a signed release, we'd recommend you use the stable build. We're not going to add signed releases for the nightly version at this time.
