### ISSUE TITLE
`latest` deb outdated

### ISSUE THREAD

**Issue by AndrewKvalheim** [wp-cli/builds#63]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

[`php-wpcli_latest_all.deb`](https://github.com/wp-cli/builds/blob/6a63ff4e95e3f2a6ce806134942e182d5f9f2296/deb/php-wpcli_latest_all.deb) points to build 2.7.1 but the latest build is 2.8.1.

**Describe how other contributors can replicate this bug**

```console
$ curl 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages/deb/php-wpcli_latest_all.deb'
php-wpcli_2.7.1_all.deb
```

**Describe what you would expect as the correct outcome**

`php-wpcli_2.8.1_all.deb`

**Comment by szepeviktor** [comment]
PR sent 🍏

**Comment by AndrewKvalheim** [comment]
Thanks, much simpler than I expected. It didn’t occur to me that this output was built manually.

**Comment by danielbachhuber** [comment]
Thanks for flagging, @AndrewKvalheim !
