### ISSUE TITLE
php-wpcli_2.9.0_all.deb cannot be installed on Debian < 12 (bookworm)

### ISSUE THREAD

**Issue by lewart3** [wp-cli/builds#66]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

php-wpcli_2.9.0_all.deb cannot be installed on Debian < 12 (bookworm)

```
$ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

$ sudo dpkg --no-act -i php-wpcli_2.9.0_all.deb 
dpkg-deb: error: archive 'php-wpcli_2.9.0_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive php-wpcli_2.9.0_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 php-wpcli_2.9.0_all.deb

$ file php-wpcli_2.8.1_all.deb php-wpcli_2.9.0_all.deb 
php-wpcli_2.8.1_all.deb: Debian binary package (format 2.0), with control.tar.xz, data compression xz
php-wpcli_2.9.0_all.deb: Debian binary package (format 2.0), with control.tar.zs, data compression zst
```

dpkg 1.21.18 added zstd support for .deb archives.
Debian 11 (bullseye) has dpkg 1.20.13.
Debian 12 (bookworm) has dpkg 1.21.22.

Please revert the data compression to xz.

Thank you!
Dan
Urbana, Illinois

**Comment by szepeviktor** [comment]
> dpkg 1.21.18 added zstd support for .deb archives.

That is right.

> Add zstd support for .deb archives.

**Comment by schlessera** [comment]
Thanks for reporting, @lewart3 !

I've pushed a fresh build with XZ compression: https://github.com/wp-cli/builds/commit/a1c4d9fa3bc6be59f2472782139190b8c0c0d053

Can you test whether this works correctly now?

**Comment by lewart3** [comment]
@schlessera , it's good now!
```
$ wp cli version
WP-CLI 2.9.0
```
Thank you, @szepeviktor and @schlessera for the speedy fix!

**Comment by swissspidy** [comment]
Glad to hear! Thanks for confirming.

**Comment by szepeviktor** [comment]
For the record: Pascal broke the Internet (again) 🙃

**Comment by lewart3** [comment]
Abolefacio, ergo sum
