### ISSUE TITLE
Publishing deb-builder script

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/builds#8]
Is it possible?
https://github.com/szepeviktor/wplib/blob/master/bin/wp-cli-updatedeb.sh
I would add headers and comments.

**Comment by danielbachhuber** [comment]
You mean include it in this repo? Probably better in the main repo, in `/utils`

**Comment by szepeviktor** [comment]
https://github.com/wp-cli/wp-cli/pull/1504
