### ISSUE TITLE
SPEC File to create rpms

### ISSUE THREAD

**Issue by duritong** [wp-cli/builds#9]
I added a specfile to create rpms, you can find it here https://github.com/duritong/wp-cli-rpm . Builds using copr here: https://copr.fedoraproject.org/coprs/duritong/wp-cli/

Maybe you want to link that somehow or even merge it somewhere?!

**Comment by danielbachhuber** [comment]
> Maybe you want to link that somehow or even merge it somewhere?!

Sure, happy to include it in the main repo, a la https://github.com/wp-cli/wp-cli/pull/1504
